# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Branch Name Check

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  which_branch:
  
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name 1
        shell: bash
        # run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        run:  echo "$(echo ${GITHUB_REF#refs/heads/})"
        # id: extract_branch1

      - name: Extract branch name 2
        shell: bash
        # run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF})"
        run: echo "$(echo ${GITHUB_HEAD_REF})"
        # id: extract_branch2

      - name: Extract branch name 3
        shell: bash
        # run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        run: echo "$(echo ${GITHUB_REF##*/})"
        # id: extract_branch3

      - name: Extract branch name 4
        shell: bash
        run: echo "$(echo ${github.event_name})"

      # - name: Extract branch name 5
      #   shell: bash
      #   run: echo $extract_branch1

      # - name: Extract branch name 6
      #   shell: bash
      #   run: echo $extract_branch2

      # - name: Extract branch name 7
      #   shell: bash
      #   run: echo $extract_branch3


      # # extract branch name
      # - name: Extract branch name
      #   if: github.event_name != 'pull_request'
      #   shell: bash
      #   run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
      #   id: extract_branch

      # # extract branch name on pull request
      # - name: Print branch name
      #   if: github.event_name == 'pull_request'
      #   run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"

      # # print branch name
      # - name: Get branch name
      #   run: echo 'The branch name is' $BRANCH_NAME