# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Staging | EMP.Api | .Net Core app deploy to EmpApi6921

on:
  push:
    branches:
      - feature-1.2.0
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'

    - name: Build with dotnet
      run: dotnet build --configuration Release ./EMP.Api

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp ./EMP.Api

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EmpApi6921'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e0926ac9911846c98d7daa8e10bebd72 }}
        package: ${{env.DOTNET_ROOT}}/myapp 
